# 特点：王者和平都能开启120帧（非插帧模式）
[templates.IQOO 12 Pro]
manufacturer = "vivo"
brand = "vivo"
model = "V2329A"
device = "V2329A"
product = "V2329A"
fingerprint = ""
name = "PD2329"
marketname = "VIVO IQOO 12 PRO"
