[templates."MEIZU 18"]
manufacturer = "meizu"
brand = "meizu"
model = "MEIZU 18"
device = "meizu18"
product = "meizu_18_CN"
fingerprint = "meizu/meizu_18_CN/meizu18:13/TKQ1.221114.001/1682814786:user/release-keys"
name = "meizu_18_CN"
packages = [
 "com.meizu.flyme.weather",
]
