[templates."MEIZU 18 Pro"]
manufacturer = "meizu"
brand = "meizu"
model = "MEIZU 18 Pro"
device = "meizu18Pro"
product = "meizu_18Pro_CN"
fingerprint = "meizu/meizu_18Pro_CN/meizu18Pro:13/TKQ1.221114.001/1682196772:user/release-keys"
name = "meizu_18Pro_CN"
packages = [
 "com.meizu.flyme.weather"
]
